name: Deploy website to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate partials
        run: node ./tools/sync-html-partials.js
        
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          protocol: ftp
          port: 21
          # Voor statische HTML direct uit repo:
          # local-dir: ./

          # Voor current subfolder:
          local-dir: ./src/

          server-dir: /thelurkinghorror/
